# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://qiita.com/")
    self.driver.set_window_size(1597, 898)
    self.driver.find_element(By.LINK_TEXT, "Bashで終了ステータスごとに異なる処理を行いたい場合にハマった").click()
    self.driver.execute_script("window.scrollTo(0,1700)")
    self.driver.execute_script("window.scrollTo(0,2973)")
    self.driver.execute_script("window.scrollTo(0,4662)")
    self.driver.find_element(By.CSS_SELECTOR, ".st-RenewalHeader_logo > svg").click()
    self.driver.find_element(By.LINK_TEXT, "「論理パーティション」の管理方法・データ構造を説明できますか？").click()
    self.driver.find_element(By.CSS_SELECTOR, ".st-RenewalHeader_logo > svg").click()
    self.driver.find_element(By.LINK_TEXT, "高い移植性と生産性を両立するソフトウェアを書くのに必要な知識と考え方 〜30年前のPOSIXシェルにも対応するシェルスクリプトはどうやって実現させたのか〜").click()
  
