# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://zenn.dev/")
    self.driver.set_window_size(1597, 898)
    self.driver.find_element(By.LINK_TEXT, "Articles").click()
    element = self.driver.find_element(By.LINK_TEXT, "Articles")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Books").click()
    element = self.driver.find_element(By.LINK_TEXT, "Books")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Scraps").click()
    element = self.driver.find_element(By.LINK_TEXT, "Scraps")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#header-search > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search_searchformField__1JsnC").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search_searchformField__1JsnC").send_keys("Docker")
    self.driver.find_element(By.CSS_SELECTOR, ".search_searchformButton__1hnWU path").click()
    self.driver.find_element(By.ID, "footer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Button_secondary__3YnG6").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_secondary__3YnG6")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
  
